# Generated by Django 6.0.1 on 2026-02-25 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('key_prefix', models.CharField(max_length=10, verbose_name='Key Prefix')),
                ('key_hash', models.CharField(max_length=255, verbose_name='Key Hash')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used At')),
            ],
            options={
                'db_table': 'api_connect_apikey',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url', models.URLField(verbose_name='Url')),
                ('events', models.JSONField(default=list, verbose_name='Events')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('secret', models.CharField(blank=True, max_length=255, verbose_name='Secret')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Triggered At')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='Failure Count')),
            ],
            options={
                'db_table': 'api_connect_webhook',
                'abstract': False,
            },
        ),
    ]
